export const navItems = [
  { to: '/', label: 'Dashboard', icon: 'dashboard' },
  { to: '/numbers', label: 'Numbers', icon: 'numbers' },
  { to: '/bulk-sender', label: 'Bulk Sender', icon: 'bulk-sender' },
  { to: '/contacts', label: 'Contacts', icon: 'contacts' },
  { to: '/templates', label: 'Templates', icon: 'templates' },
  { to: '/campaigns', label: 'Campaigns', icon: 'campaigns' },
  { to: '/chatbot', label: 'Chatbot', icon: 'chatbot' },
  { to: '/analytics', label: 'Analytics', icon: 'analytics' },
  { to: '/sheets', label: 'Sheets Sync', icon: 'sheets' },
  { to: '/groups', label: 'Groups', icon: 'groups' },
  { to: '/broadcast', label: 'Broadcast', icon: 'broadcast' },
  { to: '/auto-broadcast', label: 'Auto Broadcast', icon: 'auto-broadcast' },
  { to: '/add-members', label: 'Add Members', icon: 'add-members' },
  { to: '/settings', label: 'Settings', icon: 'settings' },
];
